# Generated by Django 5.2.12 on 2026-03-11 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('zone_code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bandwidth_mbps', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('package_type', models.CharField(choices=[('home', 'Home'), ('business', 'Business'), ('corporate', 'Corporate')], default='home', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['bandwidth_mbps'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15)),
                ('alt_phone', models.CharField(blank=True, max_length=15, verbose_name='Alt Phone')),
                ('whatsapp_number', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('nid_number', models.CharField(blank=True, max_length=20, verbose_name='NID Number')),
                ('address', models.TextField()),
                ('gps_location', models.CharField(blank=True, help_text='Latitude,Longitude', max_length=100)),
                ('connection_type', models.CharField(choices=[('fiber', 'Fiber'), ('cable', 'Cable'), ('wireless', 'Wireless')], default='fiber', max_length=20)),
                ('connection_date', models.DateField(blank=True, null=True)),
                ('pppoe_username', models.CharField(blank=True, max_length=50, verbose_name='PPPoE Username')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('mac_address', models.CharField(blank=True, max_length=17, verbose_name='MAC Address')),
                ('onu_serial', models.CharField(blank=True, max_length=50, verbose_name='ONU/Router Serial')),
                ('billing_date', models.PositiveSmallIntegerField(default=1, help_text='Day of month for billing')),
                ('monthly_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('pending', 'Pending Connection'), ('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('disconnected', 'Disconnected')], default='pending', max_length=20)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('due_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='customers.area')),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_customers', to='accounts.employee')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='customers.package')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
