# Generated by Django 5.2.12 on 2026-03-11 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tickets_access', models.CharField(choices=[('none', 'No Access'), ('view', 'View Only'), ('edit', 'View & Edit'), ('full', 'Full Access (Delete/Manage)')], default='none', max_length=10)),
                ('customers_access', models.CharField(choices=[('none', 'No Access'), ('view', 'View Only'), ('edit', 'View & Edit'), ('full', 'Full Access (Delete/Manage)')], default='none', max_length=10)),
                ('stock_access', models.CharField(choices=[('none', 'No Access'), ('view', 'View Only'), ('edit', 'View & Edit'), ('full', 'Full Access (Delete/Manage)')], default='none', max_length=10)),
                ('schedule_access', models.CharField(choices=[('none', 'No Access'), ('view', 'View Only'), ('edit', 'View & Edit'), ('full', 'Full Access (Delete/Manage)')], default='none', max_length=10)),
                ('employees_access', models.CharField(choices=[('none', 'No Access'), ('view', 'View Only'), ('edit', 'View & Edit'), ('full', 'Full Access (Delete/Manage)')], default='none', max_length=10)),
                ('accounts_finance_access', models.CharField(choices=[('none', 'No Access'), ('view', 'View Only'), ('edit', 'View & Edit'), ('full', 'Full Access (Delete/Manage)')], default='none', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='module_access', to='accounts.employee')),
            ],
            options={
                'verbose_name_plural': 'Module Access Configurations',
            },
        ),
    ]
