# Generated by Django 5.2.12 on 2026-03-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_moduleaccess_teams_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleaccess',
            name='zones_access',
            field=models.CharField(choices=[('none', 'No Access'), ('view', 'View Only'), ('edit', 'View & Edit'), ('full', 'Full Access (Delete/Manage)')], default='none', max_length=10),
        ),
    ]
