# Generated by Django 5.2.12 on 2026-03-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_moduleaccess_zones_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(db_index=True, max_length=15, unique=True),
        ),
    ]
