# Generated by Django 5.2.12 on 2026-03-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_phone_unique_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='Telegram Chat ID for notifications', max_length=50, null=True),
        ),
    ]
