# Generated by Django 5.2.12 on 2026-03-15 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_phone_unique_index'),
        ('stock', '0002_initial'),
        ('tickets', '0002_alter_ticket_assigned_team'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['transaction_type'], name='stock_stock_transac_459945_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['created_at'], name='stock_stock_created_c38b0d_idx'),
        ),
    ]
