# Generated by Django 5.2.12 on 2026-03-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_ticket_ticket_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('Cable Team (Physical Layer)', [('line_cut', 'Fiber Cut / ONU Red Light'), ('olt_down', 'OLT Down'), ('mikrotik_down', 'MikroTik Down'), ('line_shift', 'Line Shift'), ('new_connection', 'New Line (Connection)'), ('db_issue', 'DB Issue'), ('pon_fluctuation', 'PON Fluctuation'), ('adapter_issue', 'Adapter Issue (Field)')]), ('Support Team (Logical Layer)', [('router_setup', 'Router Setup'), ('speed_slow', 'Speed Issue'), ('password_change', 'Password Change'), ('tv_connect', 'TV Connect'), ('area_coverage', 'Area Coverage Inquiry'), ('line_release', 'Line Release/Cancel'), ('support_other', 'Other Support')])], max_length=30),
        ),
    ]
