# Generated by Django 5.2.12 on 2026-03-15 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_phone_unique_index'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date', 'status'], name='schedule_at_date_3da246_idx'),
        ),
    ]
